services:
  - type: web
    name: valentine-api
    env: node
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 10000
